services:
  jenkins:
    build:
      context: ./bin/${JENKINSVERSION}
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - "${HOST_MACHINE_STATS_PORT}:50000"
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:8080"
    volumes:
      - ${JENKINS_HOME}:/var/jenkins_home
